### PR TITLE
ajd chapter 12

### PR DESCRIPTION
**Pull request by alexdeas**
Animal packages!

### CODE REVIEW

**Comment by utopia-2** [comment]
This seems to have a lot of the autogenerated dist build cruft - might have been worth ignoring some of the generated files? At least those in `Animal-0.01/`.

**Comment by alexdeas** [comment]
Might be worth setting up a git ignore file for the group to catch some of the extra directories then.

**Comment by utopia-2** [comment]
Yeah, maybe. I'm not yet confident on what should or shouldn't be ignored (I got my `.gitignore` from some cpan module gitignore discussion, but I notice it's excluding some of the useful `META.*` files).

**Comment by alexdeas** [comment]
We can figure it out at the meeting.

**Pull request merged**
